version: "3.4"

services:
   liquidity-database:
      image: postgres:9.6
      container_name: database
      environment:
         - POSTGRES_PASSWORD=test
         - POSTGRES_USER=test
         - POSTGRES_DB=liquidity
      restart: always
      volumes:
         - ./crypto-liquidity-db/pgsql/cloud_db.pgsql:/docker-entrypoint-initdb.d/1-schema.sql
         - ./crypto-liquidity-db/pgsql/add-migrations-table.pgsql:/docker-entrypoint-initdb.d/2-schema.sql
         - liquidity-db-data:/var/lib/postgresql/data/
      networks:
         - liquidity-backend-network
      ports: # for debugging
         - "54321:5432"
      expose:
         - "5432"

   liquidity-service-create:
      build: .
      entrypoint: crypto-liquidity-service-create
      container_name: liquidity-service-create
      links:
         - liquidity-database
      depends_on:
         - liquidity-database
      environment:
         - DATABASE_URL=postgresql://test:test@liquidity-database:5432/liquidity?sslmode=disable
      networks:
         - liquidity-backend-network

   liquidity-service-process:
      build: .
      entrypoint: crypto-liquidity-service-process
      container_name: liquidity-service-process
      links:
         - liquidity-database
      depends_on:
         - liquidity-database
      environment:
         - DATABASE_URL=postgresql://test:test@liquidity-database:5432/liquidity?sslmode=disable
      networks:
         - liquidity-backend-network

   liquidity-web-api:
      restart: always
      build: .
      entrypoint: crypto-liquidity-web-api
      container_name: liquidity-web-api
      links:
         - liquidity-database
      depends_on:
         - liquidity-database
      environment: # TODO: different user with only read permission
         - DATABASE_URL=postgresql://test:test@liquidity-database:5432/liquidity?sslmode=disable
      networks:
         - liquidity-backend-network

   orderbook-service:
      build: .
      entrypoint: # NB: contains debug arg "max-books"
         /bin/sh -c "crypto-orderbook-service --max-retries 10 --db-max-retries 20 --db-conn \"$$DATABASE_URL\" --max-books 10"
      container_name: orderbook-service
      links:
         - liquidity-database
      depends_on:
         - liquidity-database
      environment:
         - DATABASE_URL=postgresql://test:test@liquidity-database:5432/liquidity?sslmode=disable
      networks:
         - liquidity-backend-network

networks:
   liquidity-backend-network:
      driver: bridge

volumes:
   liquidity-db-data:
