version: "3.4"

services:
   liquidity-database:
      image: postgres:9.6
      container_name: database
      environment:
         - POSTGRES_PASSWORD=test
         - POSTGRES_USER=test
         - POSTGRES_DB=liquidity
      restart: always
      volumes:
         - liquidity-db-data:/data/db
      networks:
         - liquidity-backend-network
      ports: # for debugging
         - "54321:5432"
      expose:
         - "5432"

   liquidity-service-create:
      restart: always
      build:
         context: ./crypto-liquidity-db/
         dockerfile: Dockerfile
      entrypoint: "crypto-liquidity-service-create"
      container_name: liquidity-service-create
      links:
         - liquidity-database
      depends_on:
         - liquidity-database
      environment:
         - DATABASE_URL=postgresql://test:test@liquidity-database:5432/liquidity?sslmode=disable
      networks:
         - liquidity-backend-network

   liquidity-service-process:
      restart: always
      build:
         context: ./crypto-liquidity-db/
         dockerfile: Dockerfile
      entrypoint: "crypto-liquidity-service-process"
      container_name: liquidity-service-process
      links:
         - liquidity-database
      depends_on:
         - liquidity-database
      environment:
         - DATABASE_URL=postgresql://test:test@liquidity-database:5432/liquidity?sslmode=disable
      networks:
         - liquidity-backend-network

   liquidity-web-api:
      restart: always
      build:
         context: ./crypto-liquidity-db/
         dockerfile: Dockerfile
      entrypoint: "crypto-liquidity-web-api"
      container_name: liquidity-web-api
      links:
         - liquidity-database
      depends_on:
         - liquidity-database
      environment:
         - DATABASE_URL=postgresql://test:test@liquidity-database:5432/liquidity?sslmode=disable
      networks:
         - liquidity-backend-network

   orderbook-service:
      build: # TODO
         context: ./crypto-orderbook-db-app/
         dockerfile: Dockerfile
      container_name: orderbook-service
      links:
         - liquidity-database
      depends_on:
         - liquidity-database
      environment:
         - DATABASE_URL=postgresql://test:test@liquidity-database:5432/cloud_db_clone?sslmode=disable
      networks:
         - liquidity-backend-network

networks:
   liquidity-backend-network:
      driver: bridge

volumes:
   liquidity-db-data:
