name: Docker Compose Actions Workflow

on:
  push:
    paths:
      - '**'
      - '!README.md'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Build the stack
        run: docker-compose up -d --build
