name: Docker Compose Actions Workflow

on:
  push:
    paths:
      - '**'
      - '!README.md'

jobs:
  docker-compose-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true

      # source: https://github.com/satackey/action-docker-layer-caching#docker-compose
      # Pull the latest image to build, and avoid caching pull-only images.
      # (docker pull is faster than caching in most cases.)
      - name: Pull Docker images
        run: docker-compose pull

      # source: https://github.com/satackey/action-docker-layer-caching#docker-compose
      # In this step, this action saves a list of existing images,
      # the cache is created without them in the post run.
      # It also restores the cache if it exists.
      - name: Cache Docker layers
        uses: satackey/action-docker-layer-caching@v0.0.11
        # Ignore the failure of a step and avoid terminating the job.
        continue-on-error: true

      - name: docker-compose build
        run: docker-compose up -d --build
