name: Docker Compose Actions Workflow

on:
  push:
    paths:
      - '**'
      - '!README.md'

jobs:
  docker-compose-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true

      # source: https://github.com/satackey/action-docker-layer-caching#docker-compose
      - name: Pull Docker images
        run: docker-compose pull

      - name: docker-compose clean
        run: docker-compose down && docker volume rm cryptomarketdepthcom_liquidity-db-data || exit 0

      - name: docker-compose build && run
        run: docker-compose up -d --build --scale liquidity-service-process=10

        # Try for 5 minutes until endpoint returns HTTP success
      - name: test
        # source: https://unix.stackexchange.com/a/82610/12154
        run: docker run --network container:test-service appropriate/curl /bin/sh -c 'for i in $(seq 1 60); do [ $i -gt 1 ] && sleep 5; curl --verbose --fail --retry-connrefused http://localhost:8123/test && s=0 && break || s=$?; done; (exit $s)'
