name: Docker Compose Actions Workflow

on:
  push:
    paths:
      - '**'
      - '!README.md'

jobs:
  docker-compose-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: docker-compose build
        run: docker-compose up -d --build
