name: Docker Compose Actions Workflow

on:
  push:
    paths:
      - '**'
      - '!README.md'

jobs:
  docker-compose-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true

      # source: https://github.com/satackey/action-docker-layer-caching#docker-compose
      - name: Pull Docker images
        run: docker-compose pull

      - name: docker-compose clean
        run: docker-compose down && docker volume rm cryptomarketdepthcom_liquidity-db-data || exit 0

      - name: docker-compose build && run
        run: docker-compose up -d --build

        # Try for 5 minutes until endpoint returns HTTP success
      - name: test
        run: docker run --network container:liquidity-web-api appropriate/curl --verbose --no-progress-meter --retry 60 --retry-delay 5 --retry-connrefused http://localhost:8123/test
